Section "Device"
    Identifier "LCD"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "LCDScreen"
    Device "LCD"
    DefaultDepth 16
EndSection

Section "ServerLayout"
    Identifier "DefaultLayout"
    Screen "LCDScreen"
EndSection

Section "ServerFlags"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection
